steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=$_IMAGENAME
  - --cache=true
  - --cache-ttl=10h
  - --dockerfile=./docker/full.dockerfile
  - --build-arg=target=$_FUNCTION_TARGET